name: automated-domainmodel-benchmark

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.11
  - pip
  - pip:
      - -r requirements.txt
      - ipykernel
      - notebook
      - jupyterlab
      - matplotlib
      - pandas